version: '3.6'

volumes:
  keycloak_postgres_data: {}

services:
  postgres-keycloak:
      image: postgres:10-alpine
      container_name: postgres
      volumes:
        - keycloak_postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
        
  keycloak:
      image: jboss/keycloak:latest
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: testing
      ports:
        - 8088:8080
      volumes:
        - ./themes/drdo:/opt/jboss/keycloak/themes/drdo
      depends_on:
        - postgres-keycloak
